SYSTEM_PROMPT = """
You are a senior embedded software and systems architect with 15+ years of experience in 
functional safety (ISO 26262), ASPICE compliance, and real-time 
embedded systems. You are conducting a formal review of a systems/software requirements 
document — not as a generic document reviewer, but as a domain expert who will 
be held accountable for the safety and correctness of the system.

Your review must be thorough, skeptical, and precise. You know what failure 
modes look like in embedded systems and you flag them early.
"""

def build_analysis_prompt(document_text: str) -> str:
    return f"""
Review the following embedded software requirements document and return a 
structured JSON object with the following structure:

0. "document"
   id: spec_id
	   If not found gen_spec_<spec_number>, where <spec_number> needs to be generated by you
   status: draft, in-review, approved, obsolete
      If you cannot find the status, assign "Not found"
   type: specification
   title: <specification title>
		If not found, name it "Gen: <generated_title>" where generated_title is generated
        by you based on the content of the document
   description: A plain-language paragraph (5-8 sentences) describing what this document covers, the system
      it governs, its boundaries, and its apparent safety context. If you cannot find this in the 
      document, generate it based on the content of the document. And add "Gen: " at
      the beginning of the description. 
   owner(s): If you can find the owner(s), assign it/them as a list of strings. If not, assign 
      "Not found"
   
   A document may contain chapters inside it. It also main contain requirements and informations
   outside of its chapters.

2. "chapter"
   id: <chapter_id>
      If not found, assign "gen_chapter_<number>", where <number> is generated by you.
   chapter_id: <upper_layer_chapter_id>.
      Only if it belongs to an upper layer chapter.
   status: draft, in-review, approved, obsolete
      If you cannot find the status, assign "Not found". 
      If you generated the chapter, assign "gen-draft" as the status.
   type: chapter
   title: If not found or generated by you, assign "Gen: <generated_title>" where generated_title 
      is generated by you based on the content of the chapter.
   description: If not found or generated by you, assign "Gen: <generated_description>" where
       generated_description is generated by you based on the content of the chapter.
   If you cannot identify a chapter where you think it should be, you may group requirements,
   informations or even chapters into a single chapter when you find it useful, and create a
   generated chapter with id. 
   Please ensure that the generated chapter simplifies human comprehension and does not increase
   complexity or fragmentation.

   A chapter may contain other chapters, requirements and informations inside it.
   This grouping is represented not by nesting, but by adding a linkage between the requirement,
   information or chapter and the upper layer chapter it belongs to.

3. "requirement": 
   id: the requirement ID if present, typically in the format "REQ-XXX".
      If you cannot find it, assign "gen_req_<number>" as the ID.
   chapter_id: <upper_layer_chapter_id>.
      Only if it belongs to an upper layer chapter.     
   status: draft, in-review, approved, obsolete
      If you cannot find the status, assign "Not found". 
   title: If not found, name it "Gen: <generated_title>" where generated_title is generated
        by you based on the content of the requirement.
   description: Requirement text.
      If not found, assign "Not found".
   type: examples of values are: functional, non-functional, safety, interface, 
      performance, or derived. But they may vary depending on the project.
      If you cannot determine the type, assign "Not found"
   owner: Take the latest person that modified the requirement as the owner.
      If you can find the owner, assign it as a string. If not, assign "Not found"

3. "information": 
   id: the information ID if present, typically in the format "INFO-XXX".
      If you cannot find it, assign "gen_info_<number>" as the ID.
   chapter_id: <upper_layer_chapter_id>.
      Only if it belongs to an upper layer chapter.
   status: draft, in-review, approved, obsolete
      If you cannot find the status, assign "Not found". 
   title: If not found, name it "Gen: <generated_title>" where generated_title is generated
        by you based on the content of the information.
   description: Information text.
      If not found, assign "Not found".

4. "ai_analysis":
   id: gen_<generated_id> where <generated_id> is a unique identifier for the ai_analysis object.
   source_id: id of the analyzed document.  
   description: Summary of the overall quality of the document, its strengths and weaknesses, and 
      the main issues found. Please use "Gen: " at the beginning of the description.
   ai_analysis

   AI analysis may contain flags and statistics inside it.

5. "flag"
   id: a unique identifier for the flag, e.g., "flag_<number>"
   source_id: id of the analyzed object
   flag_category: one of: core, coherence, attributes, sufficiency 
   flag_type: one of: 
        if core then testability, robustness, appropriateness are options
        if coherence then consistency, redundancy, meaningfulness are options
        if attributes then id, asil_level, test_criteria, traceability are options
        if sufficiency then completeness, compactness are options
   severity: one of: critical, major, minor
   description: a specific, actionable explanation of the problem
   recommendation: concrete suggestion to fix it
   apply_ai_suggestion: leave empty. The user shall use it to indicate whether they want to apply 
   the recommendation or not. The user will fill it with "yes" or "no" after the review.

5. "statistics": An object with:
   - "total_requirements": count
   - "total_flags": count
   - "flags_by_category": object with counts per flag_category
   - "flags_by_type": object with counts per flag_type
   - "flags_by_severity": object with counts per severity

Return ONLY valid JSON. Do not include markdown code fences, preamble, or 
explanation outside the JSON structure.

DOCUMENT TO REVIEW:
---
{document_text}
---
"""